"""Added ts column

Revision ID: 9a08378226b4
Revises: 1417ef2df792
Create Date: 2016-10-22 19:14:07.198161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a08378226b4'
down_revision = '1417ef2df792'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_log', sa.Column('ts', sa.DateTime, nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mood', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='mood_log_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='mood_log_pkey')
    )
    ### end Alembic commands ###
